project:
  type: website
  output-dir: _site

website:
  title: "mdmonowarhossain.rbind.io"
  site-url: "https://mdmonowarhossain.rbind.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: teaching.qmd
        text: Teaching & Training
      - href: projects.qmd
        text: Research & Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
