project:
  type: website
  output-dir: _site

website:
  title: "mdmonowarhossain.rbind.io"
  site-url: "https://mdmonowarhossain.rbind.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: teaching.qmd
        text: Teaching & Training
      - href: projects.qmd
        text: Research & Projects
      - href: about.qmd
        text: About
  page-footer:
    background: dark        # Makes the footer bar blue/dark like your image
    left:
      - icon: code-slash
        href: https://rpubs.com/md_monowar_hossain
    center: "Â© 2022 - 2026 Md. Monowar Hossain"
    right: 
      - icon: github
        href: https://github.com/Monowarhossainapon
      - icon: linkedin
        href: https://www.linkedin.com/in/md-monowar-hossain-apon/
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    fontsize: 1.1em
    code-copy: true

  